
export const localization = {
    en: {
        appName: "Receipt Generator",
        login: "Login",
        username: "Username",
        password: "Password",
        dashboard: "Dashboard",
        newReceipt: "New Receipt",
        receiptList: "Receipt List",
        adminPanel: "Admin Panel",
        logout: "Logout",
        searchPlaceholder: "Search by name or ID...",
        filterByDate: "Filter by date",
        exportSelected: "Export Selected",
        exportToPdf: "Export to PDF",
        exportToXlsx: "Export to XLSX",
        receiptId: "Receipt ID",
        customerName: "Customer Name",
        date: "Date",
        amount: "Amount",
        actions: "Actions",
        edit: "Edit",
        delete: "Delete",
        view: "View",
        save: "Save",
        cancel: "Cancel",
        receiptDetails: "Receipt Details",
        customerContact: "Block/Phone No.",
        items: "Items",
        addItem: "Add Item",
        description: "Description",
        quantity: "Quantity",
        unitPrice: "Unit Price",
        total: "Total",
        subtotal: "Subtotal",
        taxRate: "Tax Rate (%)",
        discount: "Discount",
        grandTotal: "Grand Total",
        paymentMethod: "Payment Method",
        cash: "Cash",
        card: "Card",
        online: "Online",
        notes: "Notes",
        confirmDelete: "Are you sure you want to delete this receipt?",
        yesDelete: "Yes, Delete",
        noCancel: "No, Cancel",
        companyName: "NEELKANTH APARTMENT VIBHAG-1",
        companySubName: "CO-OP HOUSING SERVICE SOCIETY LTD.",
        companyAddress: "BLOCK NO 1 TO 6, EWS-51, NEAR VANDE MATARAM CROSS ROAD, GOTA, AHMEDABAD",
        companyRegNo: "REG.NO CSAHDCSAHAA202500987",
        updateProfile: "Update Profile",
        profileUpdated: "Profile updated successfully!",
        displayName: "Display Name",
        organizationName: "Organization Name",
        address: "Address",
        contactNo: "Contact No.",
        regNo: "Registration No.",
    },
    gu: {
        appName: "રસીદ જનરેટર",
        login: "લોગિન",
        username: "વપરાશકર્તા નામ",
        password: "પાસવર્ડ",
        dashboard: "ડેશબોર્ડ",
        newReceipt: "નવી રસીદ",
        receiptList: "રસીદ યાદી",
        adminPanel: "એડમિન પેનલ",
        logout: "લૉગઆઉટ",
        searchPlaceholder: "નામ અથવા ID દ્વારા શોધો...",
        filterByDate: "તારીખ દ્વારા ફિલ્ટર કરો",
        exportSelected: "પસંદ કરેલ નિકાસ કરો",
        exportToPdf: "PDF માં નિકાસ કરો",
        exportToXlsx: "XLSX માં નિકાસ કરો",
        receiptId: "રસીદ ID",
        customerName: "ગ્રાહકનું નામ",
        date: "તારીખ",
        amount: "રકમ",
        actions: "ક્રિયાઓ",
        edit: "સંપાદિત કરો",
        delete: "કાઢી નાખો",
        view: "જુઓ",
        save: "સાચવો",
        cancel: "રદ કરો",
        receiptDetails: "રસીદ વિગતો",
        customerContact: "બ્લોક/ફોન નંબર",
        items: "વસ્તુઓ",
        addItem: "વસ્તુ ઉમેરો",
        description: "વર્ણન",
        quantity: "જથ્થો",
        unitPrice: "એકમ ભાવ",
        total: "કુલ",
        subtotal: "પેટાટોટલ",
        taxRate: "કર દર (%)",
        discount: "ડિસ્કાઉન્ટ",
        grandTotal: "મહાન કુલ",
        paymentMethod: "ચુકવણી પદ્ધતિ",
        cash: "રોકડ",
        card: "કાર્ડ",
        online: "ઓનલાઇન",
        notes: "નોંધો",
        confirmDelete: "શું તમે ખરેખર આ રસીદ કાઢી નાખવા માંગો છો?",
        yesDelete: "હા, કાઢી નાખો",
        noCancel: "ના, રદ કરો",
        companyName: "નીલકંઠ એપાર્ટમેન્ટ વિભાગ -૧",
        companySubName: "કો.ઓપ. હાઉસિંગ સર્વિસ સોસાયટી લિ.",
        companyAddress: "બ્લોક નંબર ૧ થી ૬, EWS-51.આઈ.સી.બી આઈલેન્ડની બાજુમાં વંદે માતરમ ચાર રસ્તા નજીક ગોતા, અમદાવાદ",
        companyRegNo: "REG.NO CSAHDCSAHAA202500987",
        updateProfile: "પ્રોફાઇલ અપડેટ કરો",
        profileUpdated: "પ્રોફાઇલ સફળતાપૂર્વક અપડેટ થઈ!",
        displayName: "પ્રદર્શન નામ",
        organizationName: "સંસ્થાનું નામ",
        address: "સરનામું",
        contactNo: "સંપર્ક નંબર",
        regNo: "નોંધણી નંબર",
    }
};
